### ISSUE TITLE
Stop receiving data

### ISSUE THREAD

**Issue by dmazzer** [dmazzer/nors-energymeter#1]
Sometimes the application stop receive data from serial port.
The branch fix_not_responding have a fix that should be tested.

**Comment by dmazzer** [comment]
`Exception in thread SensorWork:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/mazzer/nors/remote/genericsensor/genericsensor.py", line 179, in SensorWork
    sensor_data = self.ValidateSensorRead(self.SensorRead())
  File "/home/mazzer/nors/remote/sensors/nors_energymeter/sensor_energymeter.py", line 49, in SensorRead
    if self.ser.inWaiting() > 0 :
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 435, in inWaiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
IOError: [Errno 5] Input/output error
`
